# Generated by Django 5.1 on 2024-11-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesional', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='servicio_profesional',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio'),
        ),
    ]
