# Generated by Django 5.1 on 2024-11-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('profesional', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicita', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('profesional_servicio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Asignacion_Turno', models.DateTimeField()),
                ('estado_turno', models.CharField(choices=[('R', 'Rechazado'), ('A', 'Aceptado'), ('EN', 'En transcurso')], max_length=3)),
                ('solicitud', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
        ),
    ]
