# Generated by Django 5.1.1 on 2024-10-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(),
        ),
    ]
