# Generated by Django 5.1 on 2024-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('R', 'Rechazado'), ('EN', 'En transcurso'), ('A', 'Aceptado')], max_length=3),
        ),
    ]
