# Generated by Django 5.1.1 on 2024-10-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('solicitudes', '0002_alter_solicitud_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
