# Generated by Django 5.1 on 2024-11-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('solicitudes', '0003_solicitud_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('EN', 'En transcurso')], max_length=3),
        ),
    ]
