# Generated by Django 5.1 on 2024-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_turno_estado_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('EN', 'En transcurso'), ('R', 'Rechazado'), ('A', 'Aceptado')], max_length=3),
        ),
    ]
