# Generated by Django 5.1 on 2024-11-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_turno_estado_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('EN', 'En transcurso')], max_length=3),
        ),
    ]
