# Generated by Django 5.1 on 2024-11-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_turno_estado_turno'),
        ('usuarios', '0004_remove_direccion_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='solicitud_servicio',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='profesional_servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesional'),
        ),
        migrations.AddField(
            model_name='turno',
            name='solicitud',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('R', 'Rechazado'), ('A', 'Aceptado'), ('EN', 'En transcurso')], max_length=3),
        ),
        migrations.DeleteModel(
            name='SolicitudServicio',
        ),
    ]
