# Generated by Django 5.1 on 2024-11-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_remove_turno_solicitud_servicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='fecha_turno',
            new_name='fecha_Asignacion_Turno',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_solicita',
            field=models.DateTimeField(default=None),
        ),
    ]
