# Generated by Django 5.1 on 2024-11-09 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_rename_fecha_turno_turno_fecha_asignacion_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicita',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('EN', 'En transcurso')], max_length=3),
        ),
    ]
