# Generated by Django 5.1 on 2024-11-09 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_alter_solicitud_fecha_solicita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicita',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 20, 42, 34, 726422, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('A', 'Aceptado'), ('EN', 'En transcurso'), ('R', 'Rechazado')], max_length=3),
        ),
    ]
