# Generated by Django 5.1 on 2024-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_solicitud_fecha_solicita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicita',
            field=models.DateTimeField(),
        ),
    ]
