# Generated by Django 5.1 on 2024-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_alter_solicitud_fecha_solicita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('EN', 'En transcurso'), ('A', 'Aceptado'), ('R', 'Rechazado')], max_length=3),
        ),
    ]
