# Generated by Django 5.1 on 2024-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_alter_turno_estado_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado_turno',
            field=models.CharField(choices=[('R', 'Rechazado'), ('A', 'Aceptado'), ('EN', 'En transcurso')], max_length=3),
        ),
    ]
