# Generated by Django 5.1 on 2024-11-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_nombredeusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='NombreDeUsuario',
            field=models.CharField(default='', max_length=255),
        ),
    ]
