# Generated by Django 5.1 on 2024-11-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalservicio',
            name='servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
