# Generated by Django 5.1 on 2024-11-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalservicio',
            name='tipo_servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio'),
        ),
    ]
