# Generated by Django 5.1.1 on 2024-10-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='longitud',
        ),
    ]
