# Generated by Django 5.1 on 2024-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='longitud',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicio_profesional',
            field=models.ManyToManyField(to='servicios.servicio'),
        ),
    ]
