# Generated by Django 5.1.1 on 2024-10-19 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0002_remove_direccion_latitud_remove_direccion_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='servicio_profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
