# Generated by Django 5.1 on 2024-11-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0003_profesional_servicio_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='servicio_profesional',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ManyToManyField(null=True, to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=models.ManyToManyField(null=True, to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicio_profesional',
            field=models.ManyToManyField(to='servicios.servicio'),
        ),
    ]
