# Generated by Django 5.1 on 2024-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='profesional',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ManyToManyField(default=None, to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='direccion',
            field=models.ManyToManyField(default=None, to='usuarios.direccion'),
        ),
    ]
