# Generated by Django 5.1 on 2024-11-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.ManyToManyField(to='usuarios.direccion'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='direccion',
            field=models.ManyToManyField(to='usuarios.direccion'),
        ),
    ]
