# Generated by Django 5.1 on 2024-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_direccion_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profesional',
            name='localidad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profesional',
            name='provincia',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
