# Generated by Django 5.1 on 2024-11-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_profesionalservicio_tipo_servicio'),
        ('usuarios', '0005_remove_profesional_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='servicio_profesional',
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicio_profesional',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
